### PR TITLE
Revert #621 changes

### PR DESCRIPTION
**Pull request by Loilo**
Reverts changes of #621 since they were flawed by design.

```
git revert --no-commit 7f8e783
git revert --no-commit d5f182f
git commit -m "Revert #621 changes"
```

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Great. I should be at a computer within the hour. Assuming all is good I'll look to ship this as 2.3.6

**Comment by Loilo** [comment]
Hm. Seems that the CI build failed at the tests this PR removed. That's weird.

May I have overlooked something?

**Comment by johnnyreilly** [comment]
Weirdly it seems to be failing on the test that your PR removes?  Odd

**Comment by johnnyreilly** [comment]
I'm going take a gamble on this

**Comment by Loilo** [comment]
I guess/hope it's fine. The builds seemed to fail only on the removed tests. Even more strange that they only failed for two TS versions (1.7 and 2.5).

Seems like some kind of weird caching issue to me but I doubt that those "simple" bugs are still around in those established CI tools.

¯\_(ツ)_/¯

**Comment by johnnyreilly** [comment]
Problem was to do with some of the test files still hanging around (no idea why).  Should now be gone.  Just running tests locally now...

**Comment by johnnyreilly** [comment]
2.3.6 has shipped!

**Comment by Loilo** [comment]
Great. Thanks for your patience!

**Comment by johnnyreilly** [comment]
No worries - all is good now; thanks for the PR! :+1:   :1st_place_medal:

**Pull request merged**
