### PR TITLE
typecheck the error on index.ts and do the necessary convertions

### PR DESCRIPTION
**Pull request by systemmetaphor**
My proposal to fix #792

### CODE REVIEW

**Comment by systemmetaphor** [comment]
It will print something meaningful even if ts-loader catch’s a strange object as an error. I think that we can’t really trust on the error shape because some plugin might be messing things around. It will also keep the existing behavior for the expected error objects.

**Comment by johnnyreilly** [comment]
I'm not sure if I want to go to this level of error interrogation or not.  I need to think about it a little I think.

@linxiaowu66 do you have a view on this? Your approach is simpler which is initially appealing to me.  Would this PR deal with your concerns?  Does it have any advantages / disadvantages that you're aware of?

**Comment by systemmetaphor** [comment]
@johnnyreilly sure :), both options do the job, I was just guessing if it broke once due to receiving some unexpected shape it might break again on something similar

**Comment by johnnyreilly** [comment]
Thanks @systemmetaphor - I'll have a think.  I'm going to go with one of these approaches.  Just need to decide which 😄

**Comment by johnnyreilly** [comment]
Thanks for your efforts @systemmetaphor.  I've decided to go with the initial PR for simplicities sake.  I hope that's okay with you - and even though your PR hasn't landed I hope you understand why and aren't too discouraged! Much ❤️

**Comment by systemmetaphor** [comment]
:) no problem

**Pull request closed without merging**
