### PR TITLE
Fix watchpack breaking API

### LINKED ISSUE #479: watcher.mtimes undefined makes hot reload crash
Hello,

I was trying to setup a vue-ts-webpack2 stack. I have no problem with the builds, but the following error occurs when hot-reloading the build.
I use the following command : `webpack-dev-server --inline --hot`

### The tracelog
```
watch-run.js:15
        Object.keys(watcher.mtimes)
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Compiler.<anonymous> (node_modules/ts-loader/dist/watch-run.js:15:16)
    at next (node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.compilerInvalid (node_modules/webpack-dev-middleware/lib/Shared.js:144:5)
    at next (node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.compiler.plugin (node_modules/webpack/lib/CachePlugin.js:32:5)
    at Compiler.applyPluginsAsyncSeries (node_modules/tapable/lib/Tapable.js:142:13)
    at Watching._go (node_modules/webpack/lib/Compiler.js:43:16)
    at Watching.invalidate (node_modules/webpack/lib/Compiler.js:121:8)
    at Watching.<anonymous> (node_modules/webpack/lib/Compiler.js:106:8)
```

### The composer

```
{
  "name": "vuejs-app",
  "version": "1.0.0",
  "repository": {},
  "license": "MIT",
  "scripts": {
    "dev": "webpack-dev-server --inline --hot --config Resources/webpack/build/webpack.config.js "
  },
  "dependencies": {
    "css-loader": "^0.26.1",
    "less": "^2.7.2",
    "less-loader": "^2.2.3",
    "ts-loader": "^2.0.0",
    "typescript": "^2.1.6",
    "vue": "^2.1.10",
    "vue-loader": "^11.1.0",
    "vue-template-compiler": "^2.1.10",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.2.1"
  }
}
```

### The webpack config
```
const config = {
    entry: { app: './Resources/webpack/js/app.ts', },
    output: { filename: 'app.js' },
    // resolve TypeScript and Vue file
    resolve: {
        extensions: ['*', '.ts', '.vue', '.js']
    },
    module: {
        rules: [
            { test: /\.vue$/, loader: 'vue-loader' },
            { test: /\.ts$/, loader: 'ts-loader', options: { appendTsSuffixTo: [/\.vue$/] } },
        ]
    },
    plugins: []
};
```

### PR DESCRIPTION
**Pull request by bancek**
Fixes #479. A bit better than #480 #481?

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Let's give it a whirl! According to @sokra this should work.... What will the tests say?

**Comment by johnnyreilly** [comment]
https://github.com/webpack/watchpack/pull/48

**Comment by johnnyreilly** [comment]
Great! Thanks.

**Comment by bancek** [comment]
Is version bump also on the way?

**Comment by johnnyreilly** [comment]
This will probably go out as 2.0.1 - is that what you mean?

**Comment by bancek** [comment]
Yes, that's what I meant. It would be great if 2.0.1 is released as soon as possible so that semver will take care of #479.

**Comment by johnnyreilly** [comment]
yup - will see if I can get it out this evening

**Comment by johnnyreilly** [comment]
Thanks for your help - just released: https://github.com/TypeStrong/ts-loader/releases/tag/v2.0.1

**Pull request merged**
