### PR TITLE
WIP Changes for webpack 4

### PR DESCRIPTION
**Pull request by johnnyreilly**
initial migration - tests mostly failing so far.  Will seek advice

https://github.com/TypeStrong/ts-loader/issues/709

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Things to do: 

- `watch-run` will now take compiler as first parameter; change code accordingly https://github.com/webpack/webpack/releases/tag/v4.0.0-beta.0
- `fileTimestamps` is now a `Map` - https://github.com/webpack/webpack/blob/next/lib/Compiler.js#L82

Where to get startTime from?

**Comment by ekulabuhov** [comment]
Hi! Thanks for the awesome work you're doing! I've tried to run your branch with webpack 4.0.0-beta.1. 
It's a very simple clean slate project with a single file entry point "index.ts". And I'm getting this error:

https://gist.github.com/ekulabuhov/1f0a289a8e62fffd044759f31510f77b

Here's the example project: https://github.com/ekulabuhov/webpack4-test

**Comment by johnnyreilly** [comment]
Hi @ekulabuhov

I think you need to specify the ts-loader beta dependency differently. Check out this blog post:

https://blog.johnnyreilly.com/2018/01/webpack-4-ts-loader-fork-ts-checker.html?

**Comment by ekulabuhov** [comment]
Thanks @johnnyreilly ! That helped!

**Comment by johnnyreilly** [comment]
I'm going to merge this in preparation for the webpack 4 release.  I've created a `ts-loader-3` branch in case there's a need for further ts-loader / webpack 3 work.  But the expectation is it's webpack 4 from now on.

**Pull request merged**
