### PR TITLE
feat: `getCustomTransformers` support path string for a module

### PR DESCRIPTION
**Pull request by vagusX**
With happyPackMode, the customTransformers cannot be passed as undering different process.
Workaround: pass a path string to locate a js module file which export a function return the customTransformers.
Same strategy as https://github.com/s-panferov/awesome-typescript-loader/pull/531/files
Related https://github.com/TypeStrong/ts-loader/issues/739

### CODE REVIEW

**Comment by johnnyreilly** [comment]
This is terrific! Thanks so much :-) would you be able to update the readme with example usage details please? Hopefully we can use that to create a second variant of the https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/customTransformer existing test

**Comment by vagusX** [comment]
@johnnyreilly ok, I will update it asap.

**Comment by vagusX** [comment]
@johnnyreilly I've finish those jobs. You can review it where you happen to be free

**Comment by johnnyreilly** [comment]
Thanks @vagusX! Will take a look this weekend I hope

**Comment by johnnyreilly** [comment]
Released with 4.1.0

**Pull request merged**
