### PR TITLE
Protect from the mtimes property being undefined.

### PR DESCRIPTION
**Pull request by mredbishop**

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Great minds right? https://github.com/TypeStrong/ts-loader/pull/481

Thanks for this - will merge assuming tests pass. It looks like something has changed in webpack. I don't know what though.

**Comment by johnnyreilly** [comment]
Okay this was a breaking change in webpack. ts-loader depends on an undocumented part of the API. That is being added back to webpack until we  can better work around this.

**Comment by mredbishop** [comment]
Yep 🙂
at-loader has the same issue...

**Comment by johnnyreilly** [comment]
https://github.com/webpack/watchpack/pull/48

**Comment by johnnyreilly** [comment]
Thanks for your help - just released: https://github.com/TypeStrong/ts-loader/releases/tag/v2.0.1

**Comment by mredbishop** [comment]
Great, thanks John!

**Pull request closed without merging**
