### PR TITLE
Yarn pnp examples

### PR DESCRIPTION
**Pull request by johnnyreilly**
This is related to the chat here: https://github.com/arcanis/pnp-webpack-plugin/pull/10

Before merging I'll switch to use the new API implemented on my PR by @arcanis 😄

### CODE REVIEW

**Comment by arcanis** [comment]
Something wrong?

**Comment by johnnyreilly** [comment]
Nope - fat fingers!

**Comment by johnnyreilly** [comment]
Reminder to self: get this fixed up and merged

**Comment by johnnyreilly** [comment]
Done - thanks @arcanis!

**Pull request merged**
