### PR TITLE
Implement typings for CSS modules

### PR DESCRIPTION
**Pull request by MortenHoustonLudvigsen**
As suggested in #512

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Thanks for the PR - ping me when you've passing tests and I'll put aside some to review it.

**Comment by MortenHoustonLudvigsen** [comment]
Will do :-)

**Comment by MortenHoustonLudvigsen** [comment]
Right, it looks like the test for css-modules is passing now, after I made sure that the local CSS class names are predictable.

However I am still having problems with one test:

**nodeModulesMeaningfulErrorWhenImportingTs**

This test fails in AppVeyor:

* [Environment: TYPESCRIPT=typescript@2.2.1](https://ci.appveyor.com/project/jbrantly/ts-loader/build/1.0.1359/job/lgv4t5jpltxjid4s)

And in Travis:

* [Node.js: 4 TYPESCRIPT=typescript@2.2.1](https://travis-ci.org/TypeStrong/ts-loader/jobs/220328843)
* [Node.js: 5 TYPESCRIPT=typescript@2.2.1](https://travis-ci.org/TypeStrong/ts-loader/jobs/220328850)
* [Node.js: 6 TYPESCRIPT=typescript@2.2.1](https://travis-ci.org/TypeStrong/ts-loader/jobs/220328857)
* [Node.js: 7 TYPESCRIPT=typescript@2.2.1](https://travis-ci.org/TypeStrong/ts-loader/jobs/220328872)

As far as I can see this is a false negative. The reason this test fails is that the stack trace of the
expected error has changed, and that it contains file system paths. I have tried running the test with
--save-output and correcting the paths to match the previous version with no luck.

I could correct the paths to match what I see in the output from AppVeyor and Travis. But the file systems
are different, so I don't see exactly how to make the test succeed on both.

Any ideas would be appreciated!

**Comment by johnnyreilly** [comment]
If I was you I would regenerate using `--save-output` and try with that. There should be some regex "magic" which ignores platform specificity in the output.  If that doesn't work then say and I'll take a look.  Will be online tomorrow at some point.

**Comment by johnnyreilly** [comment]
Hi @MortenHoustonLudvigsen,

Let's put aside the failing test for now and I'll give some initial feedback.  First of all, thanks for contributing!  ts-loader is built by people's PRs and we're always grateful to receive them; particularly when they're as well put together as yours.

That said now I understand the purpose of your PR I'm not certain that it definitely belongs in ts-loader.  It rather feels like it should be a standalone tool which runs before ts-loader.  Looking at the implementation, everyone who uses `ts-loader`will effectively be using css-loader.  Also it creates a dependency on css-loader in ts-loader which I'm hesitant to take on.  

Have you thought about implementing this as a separate tool?  My understanding is that the real use of this is to be able to consume css modules in TypeScript.  In my head at least it makes more sense for that to be a directly implemented loader / tool rather than part of ts-loader.  What are your thoughts?  I'm open to being persuaded but at the minute I think I'm rather on the fence.

**Comment by MortenHoustonLudvigsen** [comment]
Hi @johnnyreilly 

First of all, thank you for looking at my PR. The tests are running right now, and my hope is that they should succeed after my latest commit where I expand the regex "magic" slightly. :-)

I do understand why you are on the fence, but I think there is a case for this PR. CSS is intrinsic to any web-application, and being able to import it in code is an important part of webpack. `css-loader` may be a plugin, but it is the recommended loader for CSS.

CSS Modules solve a big problem when creating component based applications (ex. with React). It makes it possible to have local CSS classes, that are _only_ available to a component. However they can not be used properly in TypeScript without typing information.

Some of the reasons I chose to create this PR in ts-loader are:

* The local css classes are only known after css-loader has run. So it is not feasible to generate typings in a prebuild step.

* A loader used with css-loader, that generates typings and writes them to disk will not work properly, because the .d.ts files can be generated after ts-loader tries to read the files.

With regards to your points

* The dependency on css-loader is a dev-dependency, and it is only there because of the test. There _is_ an assumption about what format `css-loader` returns (in `CssModule.prototype.parseClassNames`).

* I have tried to make most of the changes in `css-modules.ts`, so that changes to existing code is minimal. However, because `loader.loadModule` is async, I had to introduce an asynchronous call in the loader function: `instance.cssModules.loadCssModules(...)`. If cssModules are not enabled, this method will call the callback immediately, so there should not be any performance hit.

**Comment by MortenHoustonLudvigsen** [comment]
@johnnyreilly 

The tests are now succeeding! :-)

Thinking about it, consuming CSS Modules is a special case of creating typings for imports, that are **_not_** TypeScript.

We could get the same functionality if I create a loader to be used before ts-loader (maybe called "ts-css-loader"). This loader would then create the typings, store them in a place where ts-loader can read them, and send the TypeScript code on unchanged. ts-loader would then only have to be changed so that it could read the created typings.

With this design loaders for other types of imports would be relatively simple to implement.

What do you think?

**Comment by johnnyreilly** [comment]
> With this design loaders for other types of imports would be relatively simple to implement.

I like this as an idea.  When @HerringtonDarkholme did work to get vuejs playing nicely with ts-loader in the end we came up with the [`appendTsSuffixTo` "hook"](https://github.com/typestrong/ts-loader#appendtssuffixto-regexp-default) which allowed vue-loader and ts-loader to play well together.  (I might have some of the details wrong but that was the gist.)

**Comment by HerringtonDarkholme** [comment]
Personally, I would recommend to use TypeScript plugin to achieve such functionality.
An example will be https://github.com/sandersn/vue-ts-plugin. 

But I haven't play with plugin, but at least it seems promising.

**Comment by MortenHoustonLudvigsen** [comment]
@HerringtonDarkholme 
Thanks for the pointer! I'll have a look at it.

**Comment by HerringtonDarkholme** [comment]
Tried using css-module with `appendTsSuffixTo`. Sadly it does not work.

vue-loader works magically. It will transform a vue file to a script. To do this, it will call ts-loader to transpile script. 

When we import a `vue` file from ts file, vue-loader will first extract script from vue file and feed it to ts-loader for transpilation.  More concretely, it calls this function https://github.com/TypeStrong/ts-loader/blob/5e20c2c54cd21861b2c34c33d6cea6803de3d8f1/src/index.ts#L18.
The loader function will cache the content vue-loader passes in. And serviceHost will resolve `component.vue.ts` via cache. https://github.com/TypeStrong/ts-loader/blob/5e20c2c54cd21861b2c34c33d6cea6803de3d8f1/src/servicesHost.ts#L41-L55

However, css-loader will not call ts-loader. So the compiled css script is not visible to ts-loader. ts-loader then complains cannot find `component.css`.

**Comment by HerringtonDarkholme** [comment]
I have created a plugin for cssModule in TypeScript.

https://github.com/HerringtonDarkholme/ts-css-plugin

For now it only supports tsserver. I wonder if we can take advantage of plugin in ts-loader. 

@johnnyreilly any idea?

**Comment by MortenHoustonLudvigsen** [comment]
@HerringtonDarkholme 

Thanks for the input.

One of the reasons I decided to work on this is that there is no way to know which local CSS classes will be available in webpack before css-loader has done its magic. For example, the CSS might very well originate from less files.

So I decided that a better way of implementing (in my opinion) this is to leverage the work css-loader does by using the `loadModule` method in a loader. This is what I did in this PR, and it seems to work very well.

However, I do understand @johnnyreilly's objection to including this PR. Therefore I have started work on [ts-css-loader](https://github.com/MortenHoustonLudvigsen/ts-css-loader), that is designed to be run before ts-loader.

With regards to plugins, I had a look, and it seems that ts-loader will **_not_** load plugins (as far as I can tell they are only imported if a `ConfiguredProject` is used, which ts-loader does not do). So I don't think I can make plugins work.

My goal is for it to be possible to use for example `tsc` to build the typescript code after typings have been generated by ts-css-loader. This is why ts-css-loader writes the generated typings to `.d.ts` files.

I am pretty far. Right now a single run of webpack will create typing files, that are correctly consumed by ts-loader. Running webpack in watch mode does not work yet, however. Changing a CSS file should trigger a rebuild of the typescript file(s) that import it, and right now this does not happen.

You are very welcome to look at my code. Any comments will be welcome.

**Comment by MortenHoustonLudvigsen** [comment]
I have closed this pull request in favour of new loader [ts-css-loader](https://github.com/MortenHoustonLudvigsen/ts-css-loader). See #512

**Comment by johnnyreilly** [comment]
Well done!

**Comment by johnnyreilly** [comment]
So in the end you didn't need to make any adjustments to ts-loader for this to work?

**Comment by MortenHoustonLudvigsen** [comment]
Please see #512. I am working on a much reduced PR, that has no dependencies on anything new, but will enable ts-loader to load files from other loaders in the same chain.

**Pull request closed without merging**
