### PR TITLE
fix for declaration output to include d.ts files for interfaces

### LINKED ISSUE #174: d.ts files for interfaces missing when declarations option enabled in tsconfig.json
currently only d.ts files for .ts files referenced by webpack resources are output by ts-loader. The declarations option should also save non-class / function based d.ts files, such as those for interface objects in typescript

### PR DESCRIPTION
**Pull request by rob-bateman**
tackles the missing d.ts files for interface objects in typescript. closes #174

### CODE REVIEW

**Comment by rob-bateman** [comment]
sorry for not updating tests but the current build appears to be failing anyway. I'm not a great test whiz so any help with this would be gratefully received!

**Comment by Bartzy** [comment]
Any plans to merge this soon?

Thanks!

**Comment by jbrantly** [comment]
Yes, definitely, I've just been incredibly busy with other things recently and haven't had a lot of time to dedicate to this project. But this is a good change and will be merged and released.

**Comment by jbrantly** [comment]
Released in v0.8.2. Thanks!

**Comment by Bartzy** [comment]
@jbrantly Thanks!

I noticed that on once upgrading to 0.8.2 (from 0.8.1), Now webpack outputs full paths to asset files. Is that on purpose? It makes seeing what changed in each compilation a bit more involved.

Thanks again.

**Comment by jbrantly** [comment]
@Bartzy just to be clear, are *all* files full paths or just declaration files?

That was not an intended change and I will see about fixing in the next release (which should be very soon). v0.8.2 was released somewhat hastily just to try to fix a long standing bug but there is more that I want to get released so v0.8.3 will be following shortly.

**Comment by Bartzy** [comment]
@jbrantly Only declaration files are showing as full paths, sorry for the confusion.

**Comment by yaroslavya** [comment]
Seems like the issue persists, at least for me. I cloned this repo: `https://github.com/adrianhall/example-typescript-webpack`
then `npm install` and if I make `npm run prepublish` it generates the js files normally, but if I change the declaration to true in `tsconfig.json` then `npm run prepublish` just hangs, right after it generates the .js files. Posted it here as it looks very similar. If its not I can open another issue. For now whatever I try the ts-loader doesnt generate the `d.ts` file for my bundle and always hangs after it generated the js files.

**Comment by rob-bateman** [comment]
@jbrantly sweet, thanks for merging!

**Comment by mrblackus** [comment]
Same issue as @Bartzy here, all `d.ts` files are now generated with full absolute path *inside* build directory (the one set on webpack configuration).

@jbrantly Do you want me to open an issue for that? I didn't find one that references this error.

**Comment by jbrantly** [comment]
@mrblackus That'd be great, thanks. Apologies for the regression.

**Comment by mrblackus** [comment]
No problem, issue is open here https://github.com/TypeStrong/ts-loader/issues/186 ;)

**Pull request merged**
