### PR TITLE
WIP: Show original TS internal error (Fixes #824)

### LINKED ISSUE #824: Original TS internal error is hidden
Pulled out a more specific request from #793

### Expected Behaviour

When hitting (certain) internal TS errors such as Microsoft/TypeScript#24932 (TS 2.9.1) and Microsoft/TypeScript#26554 (TS 3.0.1), `ts-loader` attempts to get the error diagnostics which can fail with a stack like:

```
/Users/mehdibenadda/Development/fun-cms/node_modules/typescript/lib/typescript.js:107386
            return program.getOptionsDiagnostics(cancellationToken).concat(program.getGlobalDiagnostics(cancellationToken));
                           ^

TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at Object.getCompilerOptionsDiagnostics (/Users/mehdibenadda/Development/fun-cms/node_modules/typescript/lib/typescript.js:107386:28)
    at provideCompilerOptionDiagnosticErrorsToWebpack (/Users/mehdibenadda/Development/fun-cms/node_modules/ts-loader/dist/after-compile.js:39:31)
    at /Users/mehdibenadda/Development/fun-cms/node_modules/ts-loader/dist/after-compile.js:17:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mehdibenadda/Development/fun-cms/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/mehdibenadda/Development/fun-cms/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/mehdibenadda/Development/fun-cms/node_modules/webpack/lib/Compiler.js:497:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mehdibenadda/Development/fun-cms/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/mehdibenadda/Development/fun-cms/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/mehdibenadda/Development/fun-cms/node_modules/webpack/lib/Compilation.js:985:35)
...
```

### Actual Behaviour

The original TS error is reported, e.g. for Microsoft/TypeScript#26554

```
/Users/fabio/projects/0x-monorepo-one/node_modules/typescript/lib/typescript.js:14080
        return path.replace(backslashRegExp, ts.directorySeparator);
                    ^

TypeError: Cannot read property 'replace' of undefined
    at Object.normalizeSlashes (/Users/fabio/projects/0x-monorepo-one/node_modules/typescript/lib/typescript.js:14080:21)
    at getCommonSourceDirectory (/Users/fabio/projects/0x-monorepo-one/node_modules/typescript/lib/typescript.js:82737:68)
    at verifyCompilerOptions (/Users/fabio/projects/0x-monorepo-one/node_modules/typescript/lib/typescript.js:84278:27)
    at Object.createProgram (/Users/fabio/projects/0x-monorepo-one/node_modules/typescript/lib/typescript.js:82703:9)
    at Converter.convert (/Users/fabio/projects/0x-monorepo-one/node_modules/typedoc/dist/lib/converter/converter.js:109:26)
    at CliApplication.Application.convert (/Users/fabio/projects/0x-monorepo-one/node_modules/typedoc/dist/lib/application.js:84:37)
    at CliApplication.bootstrap (/Users/fabio/projects/0x-monorepo-one/node_modules/typedoc/dist/lib/cli.js:62:32)
    at CliApplication.Application [as constructor] (/Users/fabio/projects/0x-monorepo-one/node_modules/typedoc/dist/lib/application.js:44:15)
    at new CliApplication (/Users/fabio/projects/0x-monorepo-one/node_modules/typedoc/dist/lib/cli.js:38:42)
    at Object.<anonymous> (/Users/fabio/projects/0x-monorepo-one/node_modules/typedoc/bin/typedoc:4:1)
error Command failed with exit code 1.
```

### Steps to Reproduce the Problem

For Microsoft/TypeScript#26554, it should be enough to have a `ts-loader` config that looks something like:

```
{
  test: /\.tsx?$/,
  loader: 'ts-loader',
  options: {
    compilerOptions: {
      composite: true,
    }
  }
}
```

i.e. compiler options has `composite`, but not `rootDir` set.

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/Microsoft/TypeScript/issues/26554#issuecomment-415740054 links to a reproducing case.

### PR DESCRIPTION
**Pull request by simonbuchan**
See #824 for details.

Works around webpack catching thrown errors from the loader hook, and pushing them to `compilation.errors`, but not from the after-compile hook, meaning some internal TS errors get hidden by a different error.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Thanks for the PR! Unfortunately this breaks some of the error reporting; the comparison test for `errors` being a case in point. Would you like to try a different approach?

BTW is it worth splitting out the example into a separate PR or does it require your change to work?

**Comment by simonbuchan** [comment]
Yep, I expected pretty much something like that, hence it being a WIP hack 😉

The example is in a seperate commit deliberately so it could be pulled out, but I threw it in in case you would like having a repro ready to go. (You might notice it's using the local package like the test cases unlike the other examples)

As I described in the issue, I'm not sure what the right approach is here yet. If you have some ideas given that description of what's happening in happy to give it a try, or I'll do some experimenting.

But a bit late for me here tonight!

**Comment by johnnyreilly** [comment]
> or I'll do some experimenting

Experiment away! I'm on my holidays right now but I'll be watching with interest 😁

**Comment by johnnyreilly** [comment]
Closing due to inactivity

**Pull request closed without merging**
