### PR TITLE
Fix TS module resolution paths on Windows

### PR DESCRIPTION
**Pull request by smphhh**
Normalizes paths returned by TS module resolution to fix duplicate dependency issue #372 on Windows.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Thanks for contributing!  Is this ready for review or are you still working on it?

**Comment by smphhh** [comment]
It's ready.

**Comment by johnnyreilly** [comment]
Great - I'll take a look when I get a moment

**Comment by smphhh** [comment]
In one of my projects this change cut the incremental build time for a small change in the entry file from 3.5 seconds to just under one second.

**Comment by johnnyreilly** [comment]
Sweet!

**Comment by johnnyreilly** [comment]
Thanks - this is great! This will ship as part of the next release.

**Comment by smphhh** [comment]
Thanks for the quick pull :)

**Comment by johnnyreilly** [comment]
ts-loader 1.2.1 has 🚢 

https://github.com/TypeStrong/ts-loader/releases/tag/v1.2.1

**Pull request merged**
