### PR TITLE
fix: cater for change in resolveTypeReferenceDirective API in 4.7

### PR DESCRIPTION
**Pull request by dragomirtitian**
fix: cater for change in resolveTypeReferenceDirective API in TypeScript 4.7

### CODE REVIEW

**Comment by dragomirtitian** [comment]
@johnnyreilly I cherry picked your commit and made small changes. The tests seem to work locally. Don't think I can run the CI myself. Let me know if there is anything else I should do.

**Comment by johnnyreilly** [comment]
Thanks chap - I've kicked off the build and will keep an eye on it!

**Comment by johnnyreilly** [comment]
Hopefully this should ship in the next 20 mins or so: https://github.com/TypeStrong/ts-loader/releases/tag/v8.4.0

**Comment by johnnyreilly** [comment]
Live! Thanks for your help @dragomirtitian ❤️ 🌻

**Pull request merged**
