### PR TITLE
Use `typescript.sys` as the module resolution host

### PR DESCRIPTION
**Pull request by andy-ms**
But `node test/comparison-tests/run-tests.js --single-test npmLink` does not work.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Ug. Any suggestions @jbrantly?

**Comment by johnnyreilly** [comment]
Would using `typescript.sys` and falling back to the existing mechanism when it fails be a workaround that would allow us continue supporting npm link?

**Comment by HerringtonDarkholme** [comment]
If I remembered it correctly, referencing `typescript` is deliberately avoided because we don't want list TypeScript as dependency and we support other TypeScript fork implementation.

Is it still worth today? @jbrantly @johnnyreilly

**Comment by jbrantly** [comment]
Re: not referencing `typescript`, it's hard to say. I've only known 2 typescript forks, one of which is now defunct (had JSX support) and the other was originally meant to be a nightly (ntypescript) but typescript has had their own nightlies for quite a while. My leaning is that it's probably not as big of a deal.

That said, I think it's probably also not a huge deal to fix here by just doing `compiler.sys` (I think?)

Regarding breaking the npmLink test... I unfortunately don't have a lot of insight into that. The original PR implementing that is #141 if that's any help.

**Comment by johnnyreilly** [comment]
Thanks @andy-ms - this didn't get merged but the idea was used and shipped with v3.0.3 of ts-loader. The initial PR was a welcome and useful pointer so thank you.

**Pull request closed without merging**
