### PR TITLE
escaped and unescaped windows line endings normalised

### PR DESCRIPTION
**Pull request by johnnyreilly**
This is a continuation of https://github.com/TypeStrong/ts-loader/pull/138 but caught up with the latest master.  Hopefully the tests pass now....

### CODE REVIEW

**Comment by jbrantly** [comment]
Is this still failing for you personally due to the filesize issues?

**Comment by johnnyreilly** [comment]
Yes but only due to the filesize issue I mentioned:

```
      -bundle.js.map  2.54 kB       0  [emitted]  main
      +bundle.js.map  2.53 kB       0  [emitted]  main
```

I haven't looked into it but I assume that the one of the webpack options [here](https://webpack.github.io/docs/node.js-api.html#stats-tojson) could be used to prevent filesize being emitted.  Or some other jiggery pokery could be done to exclude this by hand.  

Either way I wanted to get your input on that.  What do you think is a sensible way forward that you would be happy with?  

If you're ok with excluding the file size from the tests so you get a standard test run regardless of line endings I'd be up for looking into this some more.  Your call!

**Comment by jbrantly** [comment]
Looking at the test that's failing (issue81) and all of the other tests, I believe the unique thing about issue81 is that it uses both babel-loader and sourcemaps. None of the other tests do that (some use babel but no sourcemaps, others use sourcemaps but no babel). I'm wondering then if it's a difference in the babel version. AppVeyer is running babel-loader 5.4.0.

**Comment by johnnyreilly** [comment]
Same babel version.....   Hmmmmm

**Comment by johnnyreilly** [comment]
Closing as I think this was handled elsewhere

**Pull request closed without merging**
