### PR TITLE
Fix dependency resolution when using pnpm

### LINKED ISSUE #768: When dependencies are installed with pnpm, ts-loader behaves differently than tsc
### Expected Behaviour
ts-loader should not report TS2305
### Actual Behaviour
ts-loader report TS2305 error
### Steps to Reproduce the Problem
1. clone https://github.com/xbtsw/typescript-pnpm
2. `npm i -g pnpm`
3. `pnpm install`
4. run `npm run tsc` and observe that the compilation success
5. run `npm start` and observe error

This happens to both Linux and Windows 10 host.
### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/xbtsw/typescript-pnpm

It looks like the type information is not visible to TypeScript when the dependency are symlinked and are compiled via `ts-loader`. I am willing to look into it but not sure where to start.

### PR DESCRIPTION
**Pull request by xbtsw**
* Add `realpath` to `moduleResolutionHost` so that TypeScript could follow symlink as it supposed to be
* Now that typescript follow symlink, npmLink test fails in 2.8.1 due to Microsoft/TypeScript#12358, fixed by modifying tsconfig file. (Also related to #773)
* Created a new test to cover this scenario.

Fix #768

### CODE REVIEW

**Comment by xbtsw** [comment]
I attempted to create a `execution-test` but couldn't get `pnpm` to install nested file-based dependency. [See this branch](https://github.com/xbtsw/typescript-pnpm/tree/simple) for an example:
  * The project depends on `file: pkg1`
  * `pkg1` depends on `file:../pkg2`. 

After `pnpm i`, `pkg2` couldn't be found in `node_modules`, only `pkg1` could be found. Is this expected @zkochan?

So in order to create a unit test I would need to include a real npm package that exhibits this re-export behavior, one that I know of is `office-ui-fabric-react`. I am worried it might slow down your tests too much. @johnnyreilly If you are OK then I could do that.

**Comment by zkochan** [comment]
@xbtsw the way pnpm currently works, it only symlinks directory dependencies but does not run install in the external package.

Though you can run `pnpm recursive link` in that project and it will do what you expected from `pnpm install`

**Comment by johnnyreilly** [comment]
> But I am worried that installing real packages might slow down your tests too much. @johnnyreilly If you are OK then I could do that.

I am okay with that! Go forth and conquer!

**Comment by xbtsw** [comment]
@johnnyreilly The test is added. I am ready to merge. Please kindly review and comment 🤝

**Comment by johnnyreilly** [comment]
Will do! I'm away from a keyboard for the next 5 days or so. Will check when I'm back. Thanks for your work!

**Comment by johnnyreilly** [comment]
Thanks for your work!  Released with https://github.com/TypeStrong/ts-loader/releases/tag/v4.3.0

**Pull request merged**
