### PR TITLE
add documentation for appendTsSuffixTo

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Sorry for the delay, get quite busy these days.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
No problem - thanks for this!  My machine has just died on me but once I get it up and running again I'll look at cutting a new release

**Comment by johnnyreilly** [comment]
BTW I managed to get a fix into our comparison test pack to ignore the `data-v-ab12etc` hot module hashing when performing comparisons. That's great. However it uncovered what looks like a potential issue for people on Windows using ts-loader for vuejs. On Windows absolute paths seem to be being used rather than relative ones. Do you have any ideas about this? I'll do some more digging... (Still need to commit the change to the test pack as well....)

**Comment by HerringtonDarkholme** [comment]
I would suggest this might be handled by vue-ts-loader, which I want to migrate to be a preconfigured ts-loader. It is really generous for ts-loader to support appendTsSuffix. But handling vue-specific quirks should be the task for vue-ts-loader.

**Comment by johnnyreilly** [comment]
> I just manually deleted the absolute path in output to avoid personal information leakage...:(

Ah! That makes sense :smile: I'll have a ponder about this. 

> handling vue-specific quirks should be the task for vue-ts-loader.

Agreed. Does `appendTsSuffix` actually give you something useful then? If you're not planning to make use of it then I'm pondering if it should be part of `ts-loader`. I'm totally happy for it to be but if it won't be used then I'm a little hesitant to add it.

**Comment by HerringtonDarkholme** [comment]
>  Does appendTsSuffix actually give you something useful then?

Very useful. vue-ts-loader will have to fork a copy of ts-loader if this option is not added. I can handle vue's path looking, export format or what ever vue specific in other loader. But appending suffix is simply mission impossible if no change is made underlying ts-loader.

I would even think this might be useful for hash bang file. https://github.com/TypeStrong/ts-node/issues/116

**Comment by johnnyreilly** [comment]
> Very useful. 

Then it will ship :ship: :smile:

So is the idea that `vue-ts-loader` will be chained with `ts-loader` or will `vue-ts-loader` wrap `ts-loader`?

Just so you know, the longer term aim is to join together awesome-typescript-loader and ts-loader. The initial steps of that will be ensuring both loaders support the same options. So if you need `appendTsSuffix` we want to make sure it remains supported.

**Comment by HerringtonDarkholme** [comment]
I could only implore you to keep this option. Frankly, no many users use TS + Vue. vue-ts-loader merely have 30 stars on github. And on npm only 200+ downloads last month. As a comparison, ts-loader has 294,548 downloads last month.

Yet the overhead added to ts-loader is relatively small (adding suffix if filename matches) and would hardly break other plugins ( except vue-loader), and this is the only loader I could find to support ts in vue file.

However, I can foresee that with the combination of ts-loader and ATL the code base will grow larger and many new features will be added. If the cost for this option is no longer small, I'm fine to remove it.

**Comment by johnnyreilly** [comment]
As you say: 

> the overhead added to ts-loader is relatively small

So as it stands I think it's fine and we'll include it.  If there's some reason in the future where it becomes problematic we'll certainly discuss it before taking any action.  But I'd imagine that this can carry on being supported.

**Pull request merged**
