### PR TITLE
add `"webpack": "^4.5.0"` to `peerDependencies`

### PR DESCRIPTION
**Pull request by yibuyisheng**
fix https://github.com/TypeStrong/ts-loader/issues/775

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Great! Can we change this to `4.0.0`. As far as I know it works with 4 as a minimum?

**Comment by yibuyisheng** [comment]
The webpack version in `peerDependencies` must be the same as the one in `devDependencies`, because the tests are run with the webpack version in `devDependencies`.

**Comment by johnnyreilly** [comment]
Hmmm. I don't think that's going to work then. We use a 4.x version of webpack to run the tests. Unless we switch the devDependency to be 4.0.0 as well. We could do that I guess, just rely on the yarn.lock file to enforce this. 

Actually that seems reasonable. Do you want to make the devDependency change to 4.0.0?

**Comment by johnnyreilly** [comment]
Hmmm.. some `yarn.lock` trickiness I think.

**Comment by yibuyisheng** [comment]
The test codes are breakable because it seems that they are only run well with `webpack@4.5.0`. When I changed the webpack to `4.0.0` or `4.8.3`, tests failed.

I think we should find a way to make the test codes passed with `webpack@^4.0.0`.

**Comment by yibuyisheng** [comment]
Maybe we should learn something from [babel-loader](https://github.com/babel/babel-loader/blob/master/test/loader.test.js#L56);

**Comment by johnnyreilly** [comment]
Leave it with me. When I get a moment I'll take a look

**Comment by johnnyreilly** [comment]
Closing as would now conflict with yarn PNP support

**Pull request closed without merging**
