### PR TITLE
Update to babel7

### PR DESCRIPTION
**Pull request by sa4k5hi**
Updated to babel7 in devDependencies package.json and files both in execution and comparison tests

### CODE REVIEW

**Comment by johnnyreilly** [comment]
The tests seem to be failing?

**Review by lastthyme — APPROVED** [review]

**Comment by sa4k5hi** [comment]
It seems that 2 execution test- 2.1.4_babel-react and 2.1.4_react are failing. But that is strange, because everything is working fine in local. Though I'm not sure, but I think this problem is not because of babel.

**Comment by johnnyreilly** [comment]
Seems like comparison tests are failing also? Will requeue just to be sure

**Comment by sa4k5hi** [comment]
Files only from babel-es6resolveParent, babel-issue81 and babel-issue92 comparison test has been edited. Rest is all same for it.

**Comment by sa4k5hi** [comment]
For all comparison test, it is the error-
`AssertionError [ERR_ASSERTION]: The expected output does not exist; there is nothing to compare against! Has the expected output been created?`

It seems like it is not able to identify the expected output file but is able to give actual output

**Comment by johnnyreilly** [comment]
If you can get execution tests working, I'll take a look at the comparison tests

**Comment by johnnyreilly** [comment]
Closing due to lack of activity

**Pull request closed without merging**
