### PR TITLE
Add link to typescript docs on .d.ts files

### PR DESCRIPTION
**Pull request by hawkrives**
To save people from the extreme effort of Googling for it 😉

### CODE REVIEW

**Comment by hawkrives** [comment]
Maybe nevermind; those docs aren't terribly helpful for this case.

**Comment by johnnyreilly** [comment]
Thanks chap!  I wonder if it would be worth providing an example of what that definition might look like as well?  Something like this:

```ts
declare var require: (filename: string) => any;
```

**Comment by hawkrives** [comment]
I'm more looking for an example of where to put the declaration so it's available to all the typescript files? Flow has the `flow-typed` folder for project-scope definitions, but I'm not sure where Typescript's equivalent is.

**Comment by johnnyreilly** [comment]
As long as it sits within the same folder structure as your tsconfig.json it will be detected.

**Comment by hawkrives** [comment]
I do intend to update this PR, just as soon as I figure out how convince my project to accept the example.

Ah, I figured out my problem. I'm using the DefinitelyTyped `require` already, and I'm not sure how to "extend" that definition with `require.ensure`. Should I just replace it with the sample from the docs (mostly included below)?

(I'm sorry that we're getting off the original topic of this PR, but I can submit a PR for docs on how to do this if I can ever figure it out.)

```ts
declare var require: {
    <T>(path: string): T
    (paths: string[], callback: (...modules: any[]) => void): void
    ensure: (paths: string[], callback: (require: <T>(path: string) => T) => void, chunkName?: string) => void
}
```

**Comment by hawkrives** [comment]
So after finding [this SO answer](http://stackoverflow.com/questions/12719529/using-jquery-plugin-in-typescript), I came up with this method of extending the DefinitelyTyped `require` definition:

```ts
interface Require {
    ensure: (paths: string[], callback: (require: <T>(path: string) => T) => void, chunkName?: string) => void
}
```

It seems to work! Are there any major problems with it? If not, then I might submit a PR to rework that chunk of the README.

**Comment by johnnyreilly** [comment]
I think that the require you are referring to is related to RequireJS.  Despite the similar names it's a completely different thing.  Webpack's require is commonjs and requirejs is amd...

**Comment by hawkrives** [comment]
you know, that makes a lot of sense. Well, I've successfully mixed commonjs and requirejs types, then! time to get rid of the requirejs ones. Thanks!

**Pull request merged**
