### PR TITLE
Fix name collision in experimentalWatchApi code

### LINKED ISSUE #736: experimentalWatchApi is broken in 4.0
### Expected Behaviour
`ts-loader` executes without crashing while `experimentalWatchApi` flag is set.

### Actual Behaviour
```
Module build failed: RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.
    at String.normalize (<anonymous>)
    at Object.directoryExists (d:\git\project\node_modules\ts-loader\dist\servicesHost.js:112:68)
    at Object.compilerHost.directoryExists (d:\git\project\node_modules\typescript\lib\typescript.js:77404:121)
    at d:\git\project\node_modules\typescript\lib\typescript.js:23409:22
    at Object.forEachAncestorDirectory (d:\git\project\node_modules\typescript\lib\typescript.js:11141:26)
    at getDefaultTypeRoots (d:\git\project\node_modules\typescript\lib\typescript.js:23407:12)
    at getEffectiveTypeRoots (d:\git\project\node_modules\typescript\lib\typescript.js:23393:20)
    at resolveTypeReferenceDirective (d:\git\project\node_modules\typescript\lib\typescript.js:23425:25)
    at resolveNamesWithLocalCache (d:\git\project\node_modules\typescript\lib\typescript.js:76752:38)
    at Object.resolveTypeReferenceDirectives (d:\git\project\node_modules\typescript\lib\typescript.js:76804:20)
```

### Steps to Reproduce the Problem
Enable `experimentalWatchApi`.

The issue appears to be [here](https://github.com/TypeStrong/ts-loader/blob/8b07efbb45a1b77f66839c19ace8a081355ec771/src/servicesHost.ts#L199), and repeated in the following few lines:
```ts
    directoryExists: path => compiler.sys.directoryExists(path.normalize(path)),
```

The parameter `path` is colliding with the import `path` from node.

I just tried turning this flag on as I was headed out of the office, so I'm not sure if there are other issues introduced in 4.0. I'll continue working on it tomorrow and/or next week.

### PR DESCRIPTION
**Pull request by MLoughry**
Fixes #736

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Thanks! 

Could you tell me some more about how this problem presented please? I haven't noticed a related issue being raised and so I'd like to understand the context for this.

**Comment by MLoughry** [comment]
As stated in #736, I got the following error when I turned on experimentalWatchApi:

```
Module build failed: RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.
    at String.normalize (<anonymous>)
    at Object.directoryExists (d:\git\project\node_modules\ts-loader\dist\servicesHost.js:112:68)
    at Object.compilerHost.directoryExists (d:\git\project\node_modules\typescript\lib\typescript.js:77404:121)
    at d:\git\project\node_modules\typescript\lib\typescript.js:23409:22
    at Object.forEachAncestorDirectory (d:\git\project\node_modules\typescript\lib\typescript.js:11141:26)
    at getDefaultTypeRoots (d:\git\project\node_modules\typescript\lib\typescript.js:23407:12)
    at getEffectiveTypeRoots (d:\git\project\node_modules\typescript\lib\typescript.js:23393:20)
    at resolveTypeReferenceDirective (d:\git\project\node_modules\typescript\lib\typescript.js:23425:25)
    at resolveNamesWithLocalCache (d:\git\project\node_modules\typescript\lib\typescript.js:76752:38)
    at Object.resolveTypeReferenceDirectives (d:\git\project\node_modules\typescript\lib\typescript.js:76804:20)
```

Our project previously used the happyPack mode, so we don't have any previous history to go by. But the offending change, 388f2a617d1dbdbace574b2bf0bcdd933d440e0a 8 days ago, has only been included in the 4.0.0 release from 5 days ago so far.

**Comment by johnnyreilly** [comment]
Yup - totally my bad. Me and my refactoring :smile:

Thanks for the fix; I'll merge and release this as `4.0.1`. Hopefully sometime this weekend. Thanks again for pitching in!

**Comment by johnnyreilly** [comment]
Released - thanks for your help!

**Comment by MLoughry** [comment]
No problem. I tried playing around with a fixed version locally today when I had time, but ran into hangs during webpack that I couldn't reproduce in a minimal repo (with `experimentalWatchApi`, to be clear). Are there any diagnostics I could leverage in any future investigation?

**Comment by johnnyreilly** [comment]
You could try using the trace functionality (set `traceResolution: true` in your `tsconfig.json`) which might help.  Otherwise the easiest thing to do is hack console logs into it whilst you're investigating.

Basic, but it suffices!

**Pull request merged**
