### PR TITLE
Declaration bundler plugin

### PR DESCRIPTION
**Pull request by mblandfo**
Add option to bundle files into a single .d.ts file

#263

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I'll take a look at this once we've sorted out the other PR :smile:

**Comment by mblandfo** [comment]
I'll need to add more documentation for the limitations here - typescript's compilerOptions.target must be "AMD" or "System". This is the same limitation typescript has on combining to a single outFile. Also, I think file export names must match file names.

**Comment by johnnyreilly** [comment]
First of all - well done for your work.  

However, I've been thinking about this some more and I'm not sure it makes sense for this functionality to be part of ts-loader itself.  I think it makes more sense for this to be published to npm as a separate project and maintained separately.  

I've a couple of reasons which I hope you'll understand:

1. It's not core ts-loader functionality; ts-loader is basically about taking typescript, turning into javascript and feeding it to webpack.  The plugin here is not part of that functionality and so it doesn't feel to me like it "belongs" in ts-loader.

2. There is more than one typescript webpack loader (one day I hope we'll all join together but that hasn't happened yet).  The functionality in this plugin could / should be used by anyone using any loader ideally.  If it becomes part of ts-loader then that won't be possible.

I'd be perfectly happy to have documentation in ts-loader that links to this plugin (just as we have docs that link to the `fork-ts-checker-webpack-plugin` etc)  But I don't think this functionalty should land in ts-loader directly for the reasons given.

I hope you understand my reasoning.  What do you think?

**Comment by mblandfo** [comment]
Ok, no worries, thanks for looking at this.

**Pull request closed without merging**
