### PR TITLE
fix for https://github.com/TypeStrong/ts-loader/issues/119

### PR DESCRIPTION
**Pull request by hi-q**
For now an Error instance is thrown and it is able to be used with toString properly. We got:

```javascript
Error: (15,15): error TS1144: '{' or ';' expected.,(15,17): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.,(18,1): error TS1128: Declaration or statement expected.
```
instead of [object Object], ...

### CODE REVIEW

**Comment by ForNeVeR** [comment]
+1

**Comment by jbrantly** [comment]
This seems more like an issue with webpack-stream. ts-loader creates errors that are specific for webpack formatting. webpack-stream entirely bypasses that formatting by using `stats.compilation.errors.toString()`. Instead it should really use `stats.toJson().errors`.

**Comment by hi-q** [comment]
Thank you, I have created an issue in webpack-stream and a fix:
https://github.com/shama/webpack-stream/pull/98

**Comment by jbrantly** [comment]
Looks like that was merged and published in webpack-stream. Does that mean we can close this and #190?

**Comment by hi-q** [comment]
Yes, merged, closed.
https://github.com/TypeStrong/ts-loader/issues/119

**Pull request closed without merging**
