### PR TITLE
Chore: disable GitHub Linguist detection for tests files

### PR DESCRIPTION
**Pull request by sabertazimi**
It makes TypeScript become the top language.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Could you provide some more information please? I don't understand the intent of this PR.

**Comment by sabertazimi** [comment]
> Could you provide some more information please? I don't understand the intent of this PR.

You can refer to the repo [GitHub Linguist](https://github.com/github/linguist) for GitHub language detection service.
And you can refer to the forked repo [WebPRs/ts-loader](https://github.com/WebPRs/ts-loader) for viewing live demo.

When you view original `ts-loader` repo in browser, GitHub mark `JavaScript` as top language of `ts-loader` repo
via  [GitHub Linguist](https://github.com/github/linguist) service.
But actually, all source files in `ts-loader` repo are written in `TypeScript`.
Most `JavaScript` files are located in directory `test/`.

GitHub allow you to change detection strategy in `.gitattributes` file.
After ignoring detection for files in directory `test/`,  GtiHub mark `TypeScript` as top language of `ts-loader` repo.

**Comment by sabertazimi** [comment]
type-strong

Only `ts-loader` is marked as a `JavaScript` repo. But actually, it's a `TypeScript` repo (due to all source files in directory `src/` are written in `TypeScript`).

**Review by johnnyreilly — APPROVED** [review]
Nice!

**Comment by sabertazimi** [comment]
ts-loader
type-strong2

It works.

**Pull request merged**
