### PR TITLE
fix #433, ensure deps not cleared for HMR

### LINKED ISSUE #433: Hot module reload does not work if transpileOnly is false
I finally find a reliable reproduction. 

Repo: https://github.com/HerringtonDarkholme/ts-loader-hmr

TS file

```ts
// app.ts
import {test} from './import'
console.log(test)
// import.ts
export var test = '3333333'
if (module.hot) {
  module.hot.accept()
}
```

tsconfig.json

```js
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    },
    "exclude": [
        "node_modules", "dist"
    ]
}
```

webpack config

```ts
var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './app.ts',
  output: {
    path: path.join(__dirname, 'dist'),
    publicPath: 'dist/',
    filename: 'build.js'
  },
  resolve: {
      extensions: ['.ts', '.js'],
  },

  module: {
      rules: [
          { test: /\.ts$/, use: {loader: 'ts-loader'} },
          // toggle these lines to see HMR difference
          // { test: /\.ts$/, use: {loader: 'ts-loader', options: {transpileOnly: true}} },
      ],
  },
  devServer: {
    port: 8080,
    host: 'localhost',
    watchOptions: { aggregateTimeout: 300, poll: 1000 }
  },
}
```

package.json
```
  "devDependencies": {
    "@types/webpack-env": "^1.12.1",
    "ts-loader": "^1.3.3",
    "typescript": "^2.1.4",
    "webpack": "^2.2.0-rc.3",
    "webpack-dev-server": "^2.2.0-rc.0"
  },
```

I have also compared full-compiled and transpile files. They only differs in hotCurrentHash which I don't think is a relevant point here.

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Discussed in the original issue.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I guess you're looking at the tests?

**Comment by HerringtonDarkholme** [comment]
Yes, I wonder why I cannot execute comparison test on my local machine. Turns out to be wrong TS version. Working on it.

**Comment by johnnyreilly** [comment]
Cool

**Comment by HerringtonDarkholme** [comment]
My initial observation: clearDependencies and addDependency do force refresh webpack rebuild. This is in line with my guess.

All test cases fails with at least one patch, which stands for a file change. Yet not all patches fail. 

The tricky part is: not all change effects compiled output. For example, changing `var a: any = 123` to `var a: number = 123` will not trigger webpack output because the output file does not change! So the test cases fail.

On the other hand, test like `declarationWatch` will break because the compiled js does not include declaration, so webpack will not pick change up in watch mode.

I'd rather say it is a trade-off. Forcing rebuild will ensure type/declaration errors up to date. But it also introduces more compiling overhead and breaks HMR.

**Comment by jbrantly** [comment]
It's hard to me to comment too much on the HMR side of things without really digging in deep, but I would say that keeping functionality like `declarationWatch` is pretty important. It's totally possible there is a bug somewhere in ts-loader that's breaking HMR, but ideally a fix would both resolve HMR **and** keep `declarationWatch` functionality.

You're saying that `clearDependencies` is breaking HMR. `clearDependencies` is really only there for the case where dependencies are removed from the tree, which is probably somewhat rare. I'd be interested in seeing what only using `addDependencies` would result in (so you'd still get `declarationWatch` functionality, at least for additions and changes). 

It's also possible the API changed for webpack2 and you no longer need to `clearDependencies`. And lastly it's always possible there is a bug in webpack where clearing dependencies triggers this behavior when it really shouldn't.

At the end of the day though, we need to call `addDependencies` for declaration files. That's the whole point of that API being included in webpack, to declare additional dependencies for the current file that webpack itself isn't aware of.

**Comment by HerringtonDarkholme** [comment]
But sole `addDependency` also breaks HMR.  `addDependency` has the same effect of importing a new file. And webpack gives up HMR when new files are imported. ( tested by editing local ts-loader, only removing clearDependencies also breaks HMR)

So to support both dependency watch and HMR would require managing dependencies in ts-loader (which we already have done) and adding declaration file to watch list conditionally (don't know how).

**Comment by HerringtonDarkholme** [comment]
Pushed further fix. The error diff is trivial. Maybe we need a baseline bump.

**Comment by johnnyreilly** [comment]
> The error diff is trivial. Maybe we need a baseline bump.

Do you mean the changes in the comparison tests are reasonable and don't represent a regression in functionality? If so, do you want to regenerate the necessary test results?

**Comment by HerringtonDarkholme** [comment]
Still having two errors remaining... investigating....

**Comment by HerringtonDarkholme** [comment]
Remaining failure is due to how ts-loader produces errors.

Because changing interface/ type declaration does not change output, so no webpack output is produced. However, every ts-loader error is bound to some module. If not emission is done after compilation, webpack will not produce error.

For comparison, awesome-ts-loader does not rely on compilation to report error.

**Comment by johnnyreilly** [comment]
Would it be possible to switch to that behaviour in ts-loader? I'm keen not to lose error reporting but I don't mind so much how it happens. cc @jbrantly @s-panferov - all opinions / help welcomed!

**Comment by johnnyreilly** [comment]
Not going well?

**Comment by HerringtonDarkholme** [comment]
Test is too fragile. An output relies on `stats` and error report also relies on `stats`. Output will not be emitted for stats with same hash but error reports need to be emitted every time. Output with the same hash seems undefined in webpack.

This conflict makes output annoyingly fickle. Every test run will produce different failure.

**Comment by johnnyreilly** [comment]
Frustrating...

**Comment by johnnyreilly** [comment]
Would it be worth having the new functionality behind a `hmrMode` flag and falling back to existing functionality if it's not set?  Or is that a bad idea?

**Comment by HerringtonDarkholme** [comment]
I have already done that. But it has too much breaking in tests.

**Pull request closed without merging**
