### PR TITLE
feat: generate ambient types from implementation

### LINKED ISSUE #770: TS interfaces?
### Expected Behaviour

I wonder why this module doesn't export any TS interfaces (LoaderOptions).

```ts
import { LoaderOptions } from 'ts-loader'
```

### Actual Behaviour

Just js code.

### PR DESCRIPTION
**Pull request by Hotell**
Closes #770

### CODE REVIEW

**Comment by johnnyreilly** [comment]
This is awesome! Thanks! Just waiting for tests - will plan to merge if all goes well

**Comment by Hotell** [comment]
hmm the build failed network on timeout, can you restart it please ?

**Comment by johnnyreilly** [comment]
No worries - I think Travis might be having some issues

**Comment by johnnyreilly** [comment]
Great - all passing! I'll plan to merge this and cut a release soon.

**Pull request merged**
