### PR TITLE
feat(docs): add table of contents to README

### PR DESCRIPTION
**Pull request by jsjoeio**
This PR adds a table of contents to the README (auto-generated using [`github-markdown-toc`](https://github.com/ekalinin/github-markdown-toc)).

It also makes the heading of the README look a little better. 

Resolves one task from #1024 

### Gif

Here's the package `markdown-toc` in action:
ezgif com-optimize

**UPDATE**
I automated it by adding a `pre-push` hook that runs this script:
```json
"generate-toc": "markdown-toc -i ./README.md && git add README.md && git commit -m 'chore: update docs'"
```

It's super fast! And I did `pre-push` because I figured `pre-commit` might be too much.

### CODE REVIEW

**Comment by jsjoeio** [comment]
(friendly) bump @johnnyreilly

**Comment by johnnyreilly** [comment]
Sorry I missed this Joe - been snowed! This looks super cool!!

**Comment by jsjoeio** [comment]
No worries at all! 

😂 Fair point! 

So now that you're asking, I'm second-questioning the package/tool I used...It looks like this one [`doctoc`](https://github.com/thlorenz/doctoc) might be easier to set up as a [`git hook`](https://github.com/thlorenz/doctoc#usage-as-a-git-hook) so then the TOC always stays up to date?

Let me know if you think that would be worth it, and I'll make some time to investigate this weekend.

**Comment by johnnyreilly** [comment]
Oh that sounds great! Yeah automating is always a good goal and so if you are game for looking into that I'd be super grateful!

**Comment by jsjoeio** [comment]
@johnnyreilly I got it working! 😄

Check it out. Updated the description. Open to feedback if you have any opinions on anything too!

**Comment by johnnyreilly** [comment]
Awesome! I'll try and take a look this weekend. Ping me if I forget!

**Comment by jsjoeio** [comment]
@johnnyreilly friendly ping 😄

**Comment by johnnyreilly** [comment]
Looks awesome! So this regenerates what sits between `<!-- toc -->` upon `prepush`? Nice!

**Comment by johnnyreilly** [comment]
There might be an issue with this - see linked issue

**Comment by jsjoeio** [comment]
Hoping to address in #1045

**Pull request merged**
