### PR TITLE
Speculative fix for #565

### PR DESCRIPTION
**Pull request by johnnyreilly**

### CODE REVIEW

**Comment by stephen** [comment]
@johnnyreilly - Thanks, this PR fixes the issue for me! I put together a small repro case that fails with ts 2.4.1 here: https://github.com/stephen/ts-test - applying this change passes the build again.

**Comment by johnnyreilly** [comment]
Great thanks! Planning to release this in about 3 hours time.

**Comment by HerringtonDarkholme** [comment]
@johnnyreilly Great works! This fix really saves my day!

**Comment by johnnyreilly** [comment]
Great!

**Pull request merged**
