### PR TITLE
Report errors in JS(X) files when CheckJS is enabled

### LINKED ISSUE #518: TypeScript 2.3 checkJs support
I am trying to use the new `checkJs` flag in TypeScript 2.3. When I run `tsc` standalone, I get errors from my JS files, however when I run `ts-loader`, I get no errors from my JS files.

Any idea what might be causing this?

### PR DESCRIPTION
**Pull request by schmuli**
Closes #518

### CODE REVIEW

**Comment by schmuli** [comment]
@johnnyreilly This is the PR, as discussed. I wasn't able to run the tests locally, because of Corporate proxy settings, and some tests are failing. Additionally, I didn't add any tests for this change.

**Comment by johnnyreilly** [comment]
Thanks! I think the test failure is just a flaky test (they're full integration tests and so we get the odd false negative) Just kicked off a test run again.

**Comment by johnnyreilly** [comment]
Great! Thanks for this - the fix will go out with the next release 👍

**Comment by OliverJAsh** [comment]
I'm noticing that this is reporting errors from JS files inside `node_modules`. Is that expected? I.e. I get a lot more errors running via `ts-loader` than I do when running via `tsc`.

**Comment by johnnyreilly** [comment]
Are you running with 2.2.2? Should be resolved now

**Comment by OliverJAsh** [comment]
I'm using version 2.4.1. Example of errors:

```
ERROR in ./~/react-dom/lib/ReactDOM.js
(43,3): error TS2304: Cannot find name '__REACT_DEVTOOLS_GLOBAL_HOOK__'.

ERROR in ./~/react-dom/lib/ReactDOM.js
(68,16): error TS2304: Cannot find name '__REACT_DEVTOOLS_GLOBAL_HOOK__'.

ERROR in ./~/react-dom/lib/ReactDOM.js
(82,40): error TS2551: Property 'documentMode' does not exist on type 'Document'. Did you mean 'DOCUMENT_NODE'?
```

**Comment by OliverJAsh** [comment]
Ah sorry, yes, ts-loader 2.2.2, tsc 2.4.1

**Comment by johnnyreilly** [comment]
Also are you excluding `node_modules` in your `webpack.config.js`?

**Comment by OliverJAsh** [comment]
@johnnyreilly Yes, I believe so:

``` js
{
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              // must keep this empty array so that webpack.config.development.js can push
              // hot-reloading into it
              presets: [],
              cacheDirectory: "babel-cache",
            },
          },
          {
            loader: 'ts-loader',
            options: {
              entryFileIsJs: true,
            }
          },
        ],
      },
    ]
  }
}
```

**Comment by johnnyreilly** [comment]
Hmmmm may be an issue then. If you lose the `entryFileIsJs` option does the problem resolve? (You will need to change the entry file too)

**Comment by schmuli** [comment]
You can try the `--skipLibCheck` option but I haven't checked that this changes anything.

On the other hand, I am using 2.2.2 with a big mixed project, including lots of JS in `node_modules` and I haven't seen this issue yet, so this is probably a configuration issue. What does your `tsconfig.json` look like?

**Comment by OliverJAsh** [comment]
Have you enabled checkJs on that project?

**Comment by OliverJAsh** [comment]
@schmuli @johnnyreilly I spent awhile narrowing this issue down, smallest reproduction case here https://github.com/TypeStrong/ts-loader/issues/577

**Comment by johnnyreilly** [comment]
Thanks for the repro - we appreciate it!  I wonder, could you test with ts-loader v2.2.0 please?  This was the version prior to @schmuli's change.  Does the issue arise with that version?

**Pull request merged**
