### PR TITLE
chore: upgrade webpack

### PR DESCRIPTION
**Pull request by g-plane**

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Nice - thanks! Out of curiousity, did you do this on Windows or a Mac?

**Comment by g-plane** [comment]
Yeah, I'm using Linux.

**Comment by johnnyreilly** [comment]
Nice.  Which distro?

**Comment by g-plane** [comment]
Arch Linux.

**Comment by johnnyreilly** [comment]
Fancy.  I started using Linux for the first time this year; I use Ubuntu and I'm very much enjoying it!

**Pull request merged**
