### PR TITLE
Backport #1287 to v8

### PR DESCRIPTION
**Pull request by JasonKleban**
Backport "Use caches for module resolution and type reference directives when using compiler default functions" #1287 to v8

@johnnyreilly is this the right branch for any version 8 patches?

CC @sheetalkamat

### CODE REVIEW

**Comment by johnnyreilly** [comment]
> @johnnyreilly is this the right branch for any version 8 patches?

It is yes - I've never tried publishing from a branch that isn't main using the GitHub Actions workflow.  Wonder if it works....

**Comment by johnnyreilly** [comment]
Failing comparison tests - you may want to regenerate the output for the failing tests. See https://github.com/TypeStrong/ts-loader/tree/main/test/comparison-tests#regenerating-test-data

**Comment by johnnyreilly** [comment]
I think you may have regenerated all of the test output, rather than just the failing test cases?

**Comment by JasonKleban** [comment]
I regenerated the tests, but I don't think they'll succeed on the server check happening now.  There are trivial differences and root path differences.

image

**Comment by johnnyreilly** [comment]
Yeah - I think there's something wrong with your backport

**Comment by JasonKleban** [comment]
@johnnyreilly gonna need some help please.  I don't know what I'm looking at.

**Comment by johnnyreilly** [comment]
So to regenerate the failing test I did this: `yarn run comparison-tests -- --save-output --single-test projectReferencesSymLinks`

**Comment by JasonKleban** [comment]
Yes, I ran exactly that (although I also ran "instance" since that one was also listed as failing, from my reading).

**Comment by johnnyreilly** [comment]
I did it in the context of `ts-loader`s devcontainer (but that shouldn't matter).  Looks like bad things are happening in GitHub Actions at the moment; seeing random failures

**Comment by johnnyreilly** [comment]
`yarn run comparison-tests -- --single-test projectReferencesSymLinks_WatchApi --save-output`

**Comment by JasonKleban** [comment]
good, right?

**Comment by johnnyreilly** [comment]
Yup - good.  This is where we find out if the automation works for the non-`main` branch...

**Comment by johnnyreilly** [comment]
https://github.com/TypeStrong/ts-loader/actions/runs/778506165

**Comment by johnnyreilly** [comment]
https://www.npmjs.com/package/ts-loader/v/8.2.0

**Pull request merged**
