### PR TITLE
Watch for changes on elided imports. (#156)

### LINKED ISSUE #156: Interface change doesn't trigger change in webpack
For example:

1. clone this starter kit https://github.com/AndreyUtka/angular-typescript-starter-kit
2. run web pack dev server
3. Make some change in interface 

```
export interface IHelloScope {
    displayName: string;
    style: Object;
}
```

->

```
export interface IHelloScope {
    displayName: boolean;
    style: Object;
}
```

In this case, it does not trigger update process. 

The main question is why it does not trigger an update when I made changes only in interfaces? 

Thanks.

### PR DESCRIPTION
**Pull request by jbrantly**
Currently elided imports (imports that only contain type information) are not watched by webpack. This was actually a [known issue](https://github.com/TypeStrong/ts-loader/pull/52). This PR fixes so that all imports are explicitly watched.

Resolves #156

### CODE REVIEW

**Comment by AndreyUtka** [comment]
Hi @jbrantly ,any progress for it? We are looking forward to this fix)

**Comment by jbrantly** [comment]
Current plan is to cut a release this weekend.

**Comment by johnnyreilly** [comment]
Awesome - this will be super useful on my current project!

**Comment by AndreyUtka** [comment]
thanks a lot)

**Pull request merged**
